### ISSUE TITLE
UTF-8 escaping issues

### ISSUE THREAD

**Issue by theodorton** [laserlemon/figaro#17]
Hi,

I have this config:

```
NAME:         "ØVERBYE"
ENGLISH_NAME: "OEVERBYE"
```

Ø is a Norwegian character.

The problem is that it will be escaped when accessing `ENV['NAME']`. So firing up my console gives:

```
1.9.3 (main):0 > ENV['NAME']
=> "\xC3\x98VERBYE"
1.9.3 (main):0 > ENV['NAME'].encoding
=> #<Encoding:ASCII-8BIT>
```

While the `ENGLISH_NAME`-variable will be correct and UTF-8 encoded:

```
1.9.3 (main):0 > ENV['ENGLISH_NAME']
=> "OEVERBYE"
1.9.3 (main):0 > ENV['ENGLISH_NAME'].encoding
=> #<Encoding:UTF-8>
```

Any thoughts on why this is happening?

**Comment by ragesoss** [comment]
@theodorton did you ever get to the bottom of this? I ran into something very similar... but it only happens in production via web requests, and I can't replicate it either in my development environment or via rails console in production. https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/1909

I'm stuck on debugging it, and plan to work around it by moving the relevant string somewhere besides application.yml, but I'd love to know the root cause.
