### ISSUE TITLE
How to ignore "WARNING: Skipping key" messages?

### ISSUE THREAD

**Issue by volkanunsal** [laserlemon/figaro#171]
Whenever I run a rake task on Heroku, and when I log onto Heroku console, I get these messages. It's pretty annoying. Any way to make them go away?

**Comment by erdostom** [comment]
@laserlemon this helped me catch that i committed my `application.yml`, potentially very scary!

Thank you

**Comment by schmijos** [comment]
@volkanunsal The problem is that you've checked in your `application.yml`. You should only check in a default/public version of it under a different name, e.g.: `application.example.yml`

**Comment by sakirtemel** [comment]
But what will happen if you are using application yml for servers, but you would need to override the variables for continuous integration? You can not put application.yml on your CI, so you will need to put the environment variables from CI. And at CI logs you are seeing skipping keys warnings very often. I think there could be a flag for that, at least for CI.

**Comment by laserlemon** [comment]
@sakirtemel It sounds like you're checking `application.yml` into version control. Is that right?

**Comment by sakirtemel** [comment]
@laserlemon No, while I'm initializing my container I'm copying it from application.yml.example, and the actual variables needs to be there has been sent throught CI.

**Comment by laserlemon** [comment]
So is your issue that your CI process is giving you warnings?

**Comment by sakirtemel** [comment]
Yes, something like this:

WARNING: Skipping key "DATABASE_HOST". Already set in ENV.
WARNING: Skipping key "DATABASE_PASSWORD". Already set in ENV.
WARNING: Skipping key "DATABASE_USERNAME". Already set in ENV.
WARNING: Skipping key "DATABASE_PORT". Already set in ENV.

I have another required variables which I'm setting defaults on application.yml.example. So for me I should use application.yml(which is copied from .yml.example) and override just the database and maybe some another CI related settings. And when you look at the CI logs, you're seeing the Warnings everywhere.

**Comment by laserlemon** [comment]
Unfortunately, those warnings are very intentional. What you're describing very closely mimics a potential production server scenario in which `application.yml` is used but some pre-existing environment variable exists on the server. You can safely ignore those warning messages if you're aware of the collision (which you are, of course). I'd also consider a pull request that silences these warnings based on the presence of some environment variable such as `ENV["FIGARO_SILENCE_WARNINGS"]`.

**Comment by sakirtemel** [comment]
Yes, I've read the comments above. But I think for production servers it should stay like this, it's good to have warnings, they could lead to avoid using environment variables when Figaro is there, so maybe people will use Figaro instead of ENVs.

I was thinking about `ENV["CI_SERVER"]` or `ENV["CI"]` flag, which are automatically set by CI servers. I don't think that this warning message would be useful for any CI logs. What do you think?

**Comment by laserlemon** [comment]
I don't know if we can rely on `ENV["CI"]` in all cases. If you're experiencing these unwanted warnings, we do know that you have access to setting your own `ENV` variables so setting something like `ENV["FIGARO_SILENCE_WARNINGS"]` wouldn't be unreasonable. Plus, there could be cases where one might _want_ to see the warnings on CI.

**Comment by sakirtemel** [comment]
I know this flag from bower (http://bower.io/docs/api/#running-on-a-continuous-integration-server). And Gitlab CI sets `CI=true`, too. I couldn't see any cases someone would want to see those warnings on CI logs. And since we're running some rake commands on CIs it's becoming uglier, and becoming harder to read the exact logs(for 5 rake tasks I'm seeing 5x7 warnings)

`FIGARO_SILENCE_WARNING` would also work me, but as I told forcing the users to use only one place to set the variables would be a good idea.

**Comment by laserlemon** [comment]
I don't know what you mean by your last sentence. What do you mean by "forcing the users to use only one place to set the variables"?

**Comment by sakirtemel** [comment]
Well, I have explained it wrong , sorry. I mean if they see this warning
message on production, then when they look for the solution for it , they
would see the explanation of yours that it's not the correct way to go.
https://github.com/laserlemon/figaro/issues/171#issuecomment-62996529

**Comment by laserlemon** [comment]
I don't think we'll end up forcing one approach or the other. But where there are collisions, we _should_ warn unless the developer explicitly opts to silence those warnings.

**Comment by sakirtemel** [comment]
Ok, but maybe adding your comment to Readme will be nice. I still like to
explain to the developers why this warning is there.

And another thing, CI could be solved like this: if ci flag is on and
suppress is not there, it will suppress the warnings. If ci is on but
suppress is false, then they could see the warnings even in CI. This is
just my suggestion.

**Comment by schmijos** [comment]
:+1: for the `FIGARO_SILENCE_WARNING` environment variable. But maybe there should be an extended log level concept?

**Comment by theasteve** [comment]
when I run ```rails server``` I get WARNING: Skipping key "TWILIO_AUTH_TOKEN". Already set in ENV. I have an application.yml but I have not deploy to Heroku. How can I go about solving this issue?

**Comment by laserlemon** [comment]
Have you explicitly put `Figaro.load` in your app anywhere? Does it give you that warning for every key in your `application.yml`?

**Comment by theasteve** [comment]
I believe I have not put Figaro.load anywhere in the app and it does give me a warning for every key in the application.yml

**Comment by laserlemon** [comment]
What version of Figaro are you using?

**Comment by theasteve** [comment]
I am using Figaro (1.1.1)  with Ruby 2.2.0p0

**Comment by laserlemon** [comment]
What do you see if you run `echo $TWILIO_AUTH_TOKEN` from the command line?

**Comment by theasteve** [comment]
I see the Token 68ce616*********************

**Comment by laserlemon** [comment]
Somehow those variables are set in your actual ENV, so the warning from Figaro is important because it's going to use what you saw above rather than whatever you put in `application.yml`.

**Comment by theasteve** [comment]
should I erase the application.yml file?

**Comment by theasteve** [comment]
I run ```unset TWILIO_ACCOUNT_SID``` and now when I run ```echo $TWILIO_AUTH_TOKEN``` I get nothing back.

**Comment by laserlemon** [comment]
Now that they're unset, do you still get the warnings when running `rails server`?
