### ISSUE TITLE
Slimming down for Rails 4.1

### ISSUE THREAD

**Issue by krainboltgreene** [laserlemon/figaro#84]
Now that Rails 4.1 does 50% of what figaro does it might be smart to remove that for a major version release and focus on the other parts of the gem.

**Comment by saneshark** [comment]
Rails uses environment variables for production via ERB `<%= ENV[...] %>`
One could easily do the same for other environments (ie. staging). This is convention vs configuration at its finest. I no longer see a compelling reason to fight it. Looks like this thread hasn't had much feedback since 2013. Curious to hear what makes Figaro particularly viable? Have the Pros and Cons changed?
